name: Build docker image

on:
  pull_request:
    branches:
      - "0.6.9"
    paths:
      - api/Dockerfile

concurrency:
  group: docker-build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service_name: "api-amd64"
            platform: linux/amd64
            context: "api"
          - service_name: "api-arm64"
            platform: linux/arm64
            context: "api"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: ${{ matrix.context }}
          platforms: ${{ matrix.platform }}
          tags: leyuanqaq/intelligent-app:${{ matrix.service_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
